### ISSUE TITLE
Verify user access in h_api.py

### ISSUE THREAD

**Issue by gvseghbr** [IBCNServices/tengu-charms#13]
Currently [h_api.py](https://github.com/IBCNServices/tengu-charms/blob/master/charms/layers/hauchiwa/files/tengu_management/scripts/h_api.py) only checks with Google if the token is a valid token. It then saves the google user id.
The code also needs to verify whether the user is allowed access.
A possible solution, add list of allowed user ids to the service's settings. Fill in this setting first with the user that created the hauchiwa. With this method it is easy to add extra users that can see the model, by simply adding them to the list.

**Comment by galgalesh** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Authentication](https://trello.com/c/WrtTOWSb/3-authentication)
